# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SqActv.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormActv(object):
    def setupUi(self, FormActv):
        FormActv.setObjectName("FormActv")
        FormActv.resize(400, 300)
        FormActv.setStyleSheet("background-color: #DDF0FD;")
        self.tituloActv = QtWidgets.QLabel(FormActv)
        self.tituloActv.setGeometry(QtCore.QRect(61, 30, 261, 37))
        self.tituloActv.setStyleSheet("color: black;\n"
"background-color: #41AEF9;")
        self.tituloActv.setText("")
        self.tituloActv.setAlignment(QtCore.Qt.AlignCenter)
        self.tituloActv.setObjectName("tituloActv")
        self.pregunta3 = QtWidgets.QLabel(FormActv)
        self.pregunta3.setGeometry(QtCore.QRect(104, 200, 150, 25))
        self.pregunta3.setStyleSheet("background-color: #BAE1FC;\n"
"")
        self.pregunta3.setText("")
        self.pregunta3.setAlignment(QtCore.Qt.AlignCenter)
        self.pregunta3.setObjectName("pregunta3")
        self.respuestas1 = QtWidgets.QComboBox(FormActv)
        self.respuestas1.setGeometry(QtCore.QRect(36, 146, 141, 25))
        self.respuestas1.setStyleSheet("background-color: white;")
        self.respuestas1.setObjectName("respuestas1")
        self.respuestas2 = QtWidgets.QComboBox(FormActv)
        self.respuestas2.setGeometry(QtCore.QRect(209, 146, 141, 25))
        self.respuestas2.setStyleSheet("background-color: white;")
        self.respuestas2.setObjectName("respuestas2")
        self.respuestas3 = QtWidgets.QComboBox(FormActv)
        self.respuestas3.setGeometry(QtCore.QRect(104, 230, 150, 25))
        self.respuestas3.setStyleSheet("background-color: white;")
        self.respuestas3.setObjectName("respuestas3")
        self.aceptar = QtWidgets.QPushButton(FormActv)
        self.aceptar.setGeometry(QtCore.QRect(160, 260, 30, 30))
        self.aceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aceptar.setStyleSheet("background-color: white;\n"
"border-radius: 10;")
        self.aceptar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aceptar.setIcon(icon)
        self.aceptar.setObjectName("aceptar")
        self.pregunta1 = QtWidgets.QTextBrowser(FormActv)
        self.pregunta1.setGeometry(QtCore.QRect(27, 80, 150, 61))
        self.pregunta1.setStyleSheet("background-color: #BAE1FC;\n"
"")
        self.pregunta1.setObjectName("pregunta1")
        self.pregunta2 = QtWidgets.QTextBrowser(FormActv)
        self.pregunta2.setGeometry(QtCore.QRect(200, 80, 150, 61))
        self.pregunta2.setStyleSheet("background-color: #BAE1FC;")
        self.pregunta2.setObjectName("pregunta2")

        self.retranslateUi(FormActv)
        QtCore.QMetaObject.connectSlotsByName(FormActv)

    def retranslateUi(self, FormActv):
        _translate = QtCore.QCoreApplication.translate
        FormActv.setWindowTitle(_translate("FormActv", "Form"))
        self.pregunta1.setHtml(_translate("FormActv", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pregunta2.setHtml(_translate("FormActv", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
