# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SqCaracter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormCaracter(object):
    def setupUi(self, FormCaracter):
        FormCaracter.setObjectName("FormCaracter")
        FormCaracter.resize(400, 300)
        FormCaracter.setStyleSheet("background-color: #FFD0B2;")
        self.tituloCaracteristicas = QtWidgets.QLabel(FormCaracter)
        self.tituloCaracteristicas.setGeometry(QtCore.QRect(60, 40, 261, 37))
        self.tituloCaracteristicas.setStyleSheet("background-color: #FFBB90;\n"
"border-radius: 10;")
        self.tituloCaracteristicas.setText("")
        self.tituloCaracteristicas.setAlignment(QtCore.Qt.AlignCenter)
        self.tituloCaracteristicas.setObjectName("tituloCaracteristicas")
        self.pregunta1 = QtWidgets.QTextBrowser(FormCaracter)
        self.pregunta1.setGeometry(QtCore.QRect(30, 100, 201, 61))
        self.pregunta1.setStyleSheet("background-color: #FFD0B2;\n"
"")
        self.pregunta1.setObjectName("pregunta1")
        self.respuestas1 = QtWidgets.QComboBox(FormCaracter)
        self.respuestas1.setGeometry(QtCore.QRect(40, 170, 141, 25))
        self.respuestas1.setStyleSheet("background-color: white;")
        self.respuestas1.setObjectName("respuestas1")
        self.aceptar = QtWidgets.QPushButton(FormCaracter)
        self.aceptar.setGeometry(QtCore.QRect(180, 250, 30, 30))
        self.aceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aceptar.setStyleSheet("background-color: white;\n"
"border-radius: 10;")
        self.aceptar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aceptar.setIcon(icon)
        self.aceptar.setObjectName("aceptar")
        self.pregunta2 = QtWidgets.QTextBrowser(FormCaracter)
        self.pregunta2.setGeometry(QtCore.QRect(220, 180, 150, 31))
        self.pregunta2.setStyleSheet("background-color: #FFD0B2;\n"
"")
        self.pregunta2.setObjectName("pregunta2")
        self.respuestas2 = QtWidgets.QComboBox(FormCaracter)
        self.respuestas2.setGeometry(QtCore.QRect(230, 220, 141, 25))
        self.respuestas2.setStyleSheet("background-color: white;")
        self.respuestas2.setObjectName("respuestas2")

        self.retranslateUi(FormCaracter)
        QtCore.QMetaObject.connectSlotsByName(FormCaracter)

    def retranslateUi(self, FormCaracter):
        _translate = QtCore.QCoreApplication.translate
        FormCaracter.setWindowTitle(_translate("FormCaracter", "Form"))
        self.pregunta1.setHtml(_translate("FormCaracter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pregunta2.setHtml(_translate("FormCaracter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
