# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SqClima.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormClima(object):
    def setupUi(self, FormClima):
        FormClima.setObjectName("FormClima")
        FormClima.resize(400, 300)
        FormClima.setStyleSheet("background-color: #E1F5C3;")
        self.pregunta2 = QtWidgets.QTextBrowser(FormClima)
        self.pregunta2.setGeometry(QtCore.QRect(200, 140, 171, 51))
        self.pregunta2.setStyleSheet("background-color: #DBFFA6;\n"
"")
        self.pregunta2.setObjectName("pregunta2")
        self.pregunta1 = QtWidgets.QTextBrowser(FormClima)
        self.pregunta1.setGeometry(QtCore.QRect(20, 100, 151, 51))
        self.pregunta1.setStyleSheet("background-color: #DBFFA6;\n"
"")
        self.pregunta1.setObjectName("pregunta1")
        self.respuestas1 = QtWidgets.QComboBox(FormClima)
        self.respuestas1.setGeometry(QtCore.QRect(30, 160, 141, 25))
        self.respuestas1.setStyleSheet("background-color: white;")
        self.respuestas1.setObjectName("respuestas1")
        self.tituloClima = QtWidgets.QLabel(FormClima)
        self.tituloClima.setGeometry(QtCore.QRect(60, 30, 261, 37))
        self.tituloClima.setStyleSheet("background-color: #C4FD6F;\n"
"border-radius: 10;")
        self.tituloClima.setText("")
        self.tituloClima.setAlignment(QtCore.Qt.AlignCenter)
        self.tituloClima.setObjectName("tituloClima")
        self.aceptar = QtWidgets.QPushButton(FormClima)
        self.aceptar.setGeometry(QtCore.QRect(170, 240, 30, 30))
        self.aceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aceptar.setStyleSheet("background-color: white;\n"
"border-radius: 10;")
        self.aceptar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aceptar.setIcon(icon)
        self.aceptar.setObjectName("aceptar")
        self.respuestas2 = QtWidgets.QComboBox(FormClima)
        self.respuestas2.setGeometry(QtCore.QRect(220, 200, 151, 25))
        self.respuestas2.setStyleSheet("background-color: white;")
        self.respuestas2.setObjectName("respuestas2")

        self.retranslateUi(FormClima)
        QtCore.QMetaObject.connectSlotsByName(FormClima)

    def retranslateUi(self, FormClima):
        _translate = QtCore.QCoreApplication.translate
        FormClima.setWindowTitle(_translate("FormClima", "Form"))
        self.pregunta2.setHtml(_translate("FormClima", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pregunta1.setHtml(_translate("FormClima", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
