# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SqMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(485, 395)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnTam = QtWidgets.QPushButton(self.centralwidget)
        self.btnTam.setGeometry(QtCore.QRect(120, 115, 111, 81))
        self.btnTam.setStyleSheet("")
        self.btnTam.setText("")
        self.btnTam.setObjectName("btnTam")
        self.btnActividad = QtWidgets.QPushButton(self.centralwidget)
        self.btnActividad.setGeometry(QtCore.QRect(255, 115, 111, 81))
        self.btnActividad.setText("")
        self.btnActividad.setObjectName("btnActividad")
        self.btnClima = QtWidgets.QPushButton(self.centralwidget)
        self.btnClima.setGeometry(QtCore.QRect(255, 220, 111, 81))
        self.btnClima.setText("")
        self.btnClima.setObjectName("btnClima")
        self.btnCaracter = QtWidgets.QPushButton(self.centralwidget)
        self.btnCaracter.setGeometry(QtCore.QRect(120, 220, 111, 81))
        self.btnCaracter.setText("")
        self.btnCaracter.setObjectName("btnCaracter")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(120, 30, 241, 41))
        self.titulo.setText("")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.tituloCompatibilidad = QtWidgets.QLabel(self.centralwidget)
        self.tituloCompatibilidad.setGeometry(QtCore.QRect(170, 320, 149, 32))
        self.tituloCompatibilidad.setText("")
        self.tituloCompatibilidad.setAlignment(QtCore.Qt.AlignCenter)
        self.tituloCompatibilidad.setObjectName("tituloCompatibilidad")
        self.btnCompatibilidad = QtWidgets.QPushButton(self.centralwidget)
        self.btnCompatibilidad.setGeometry(QtCore.QRect(290, 324, 25, 25))
        self.btnCompatibilidad.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/flecha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCompatibilidad.setIcon(icon)
        self.btnCompatibilidad.setObjectName("btnCompatibilidad")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 485, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
